# Jekyll configuration flags. Accessible: {{ site.name }}
name: Peter Etelej
description: Let's Talk Code
avatar: https://avatars3.githubusercontent.com/u/2271973?v=3&s=96
footer-links:
  facebook: peter.etelej
  flickr: etelej
  github: peteretelej
  linkedin: peteretelej
  rss: https://peteretelej.github.io/feed.xml
  sitemap: https://peteretelej.github.io/sitemap.xml
  twitter: peteretelej
  stackoverflow: users/1209272/peter-etelej
disqus: etelejgithub
google_analytics: UA-54941457-1
url: https://peteretelej.github.io
baseurl: ""
markdown: kramdown
highlighter: rouge # githubpages supports rouge
permalink: /:title/
# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed
gems:
  - jemoji 
  - jekyll-sitemap 

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
